apiVersion: v1
kind: Service
metadata:
  name: restapp-service
spec:
  type: NodePort
  selector:
    app: restapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30419  # Optional: you can omit this to let Kubernetes assign a random port
